name: PR

on:
  pull_request:
    types: [assigned, unassigned, labeled, unlabeled, opened, edited, closed, reopened, synchronize, converted_to_draft, ready_for_review, locked, unlocked, review_requested, review_request_removed]

jobs:

  tests:
    name: Notify
    runs-on: ubuntu-latest
    steps:

    - name: Send Notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          User @${{ github.actor }} updated PR #${{ github.event.number }}, new state is: ${{ github.event.action }} (${{ github.event.pull_request.url }})
